/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleHotelsRouteImport } from './routes/$locale/hotels'
import { Route as LocaleFlightsRouteImport } from './routes/$locale/flights'
import { Route as Locale404RouteImport } from './routes/$locale/404'
import { Route as LocaleUserRouteRouteImport } from './routes/$locale/user/route'
import { Route as LocaleUserIndexRouteImport } from './routes/$locale/user/index'
import { Route as LocaleHotelsIndexRouteImport } from './routes/$locale/hotels.index'
import { Route as LocaleFlightsIndexRouteImport } from './routes/$locale/flights.index'
import { Route as LocaleUserTripsRouteImport } from './routes/$locale/user/trips'
import { Route as LocaleUserSettingsRouteImport } from './routes/$locale/user/settings'
import { Route as LocaleUserSavedRouteImport } from './routes/$locale/user/saved'
import { Route as LocaleUserRewardsRouteImport } from './routes/$locale/user/rewards'
import { Route as LocaleUserReviewRouteImport } from './routes/$locale/user/review'
import { Route as LocaleUserAccountRouteImport } from './routes/$locale/user/account'
import { Route as LocaleHotelsSearchRouteImport } from './routes/$locale/hotels.search'
import { Route as LocaleFlightsSearchRouteImport } from './routes/$locale/flights.search'
import { Route as LocaleDestinationsPromoRouteImport } from './routes/$locale/destinations/promo'
import { Route as LocaleDestinationsCountryRouteImport } from './routes/$locale/destinations/country'
import { Route as LocaleAuthSignUpRouteImport } from './routes/$locale/auth/sign-up'
import { Route as LocaleAuthSignInRouteImport } from './routes/$locale/auth/sign-in'
import { Route as LocaleInfoTrustSafetyRouteImport } from './routes/$locale/_info/trust-safety'
import { Route as LocaleInfoTermsConditionsRouteImport } from './routes/$locale/_info/terms-conditions'
import { Route as LocaleInfoPrivacyPolicyRouteImport } from './routes/$locale/_info/privacy-policy'
import { Route as LocaleInfoHelpCenterRouteImport } from './routes/$locale/_info/help-center'
import { Route as LocaleInfoCustomerServiceRouteImport } from './routes/$locale/_info/customer-service'
import { Route as LocaleInfoContactRouteImport } from './routes/$locale/_info/contact'
import { Route as LocaleInfoAboutRouteImport } from './routes/$locale/_info/about'
import { Route as LocaleBookingReserveRouteRouteImport } from './routes/$locale/_booking/reserve/route'
import { Route as LocaleBookingCheckoutRouteRouteImport } from './routes/$locale/_booking/checkout/route'
import { Route as LocaleHotelsSearchIndexRouteImport } from './routes/$locale/hotels.search.index'
import { Route as LocaleFlightsSearchIndexRouteImport } from './routes/$locale/flights.search.index'
import { Route as LocaleHotelsCountryIdHotelIdRouteImport } from './routes/$locale/hotels.$countryId.$hotelId'
import { Route as LocaleBookingCheckoutFlightIdRouteImport } from './routes/$locale/_booking/checkout/$flightId'
import { Route as LocaleBookingConfirmationWebCheckinRouteImport } from './routes/$locale/_booking/_confirmation/web-checkin'
import { Route as LocaleBookingConfirmationOrderDetailRouteImport } from './routes/$locale/_booking/_confirmation/order-detail'
import { Route as LocaleBookingConfirmationFlightDetailsRouteImport } from './routes/$locale/_booking/_confirmation/flight-details'
import { Route as LocaleBookingConfirmationConfirmationHotelRouteImport } from './routes/$locale/_booking/_confirmation/confirmation-hotel'
import { Route as LocaleBookingConfirmationConfirmationFlightRouteImport } from './routes/$locale/_booking/_confirmation/confirmation-flight'
import { Route as LocaleBookingConfirmationConfirmationRouteImport } from './routes/$locale/_booking/_confirmation/confirmation'
import { Route as LocaleBookingReservePaymentBookingIdRouteImport } from './routes/$locale/_booking/reserve/payment.$bookingId'
import { Route as LocaleBookingReserveFormBookingIdRouteImport } from './routes/$locale/_booking/reserve/form.$bookingId'
import { Route as LocaleBookingCheckoutTicketTypeFlightIdRouteImport } from './routes/$locale/_booking/checkout/ticket-type.$flightId'
import { Route as LocaleBookingCheckoutSeatsFlightIdRouteImport } from './routes/$locale/_booking/checkout/seats.$flightId'
import { Route as LocaleBookingCheckoutPaymentFlightIdRouteImport } from './routes/$locale/_booking/checkout/payment.$flightId'
import { Route as LocaleBookingCheckoutPaxFlightIdRouteImport } from './routes/$locale/_booking/checkout/pax.$flightId'
import { Route as LocaleBookingCheckoutExtrasFlightIdRouteImport } from './routes/$locale/_booking/checkout/extras.$flightId'

const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleHotelsRoute = LocaleHotelsRouteImport.update({
  id: '/hotels',
  path: '/hotels',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleFlightsRoute = LocaleFlightsRouteImport.update({
  id: '/flights',
  path: '/flights',
  getParentRoute: () => LocaleRoute,
} as any)
const Locale404Route = Locale404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleUserRouteRoute = LocaleUserRouteRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleUserIndexRoute = LocaleUserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleUserRouteRoute,
} as any)
const LocaleHotelsIndexRoute = LocaleHotelsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleHotelsRoute,
} as any)
const LocaleFlightsIndexRoute = LocaleFlightsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleFlightsRoute,
} as any)
const LocaleUserTripsRoute = LocaleUserTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => LocaleUserRouteRoute,
} as any)
const LocaleUserSettingsRoute = LocaleUserSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LocaleUserRouteRoute,
} as any)
const LocaleUserSavedRoute = LocaleUserSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => LocaleUserRouteRoute,
} as any)
const LocaleUserRewardsRoute = LocaleUserRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => LocaleUserRouteRoute,
} as any)
const LocaleUserReviewRoute = LocaleUserReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => LocaleUserRouteRoute,
} as any)
const LocaleUserAccountRoute = LocaleUserAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => LocaleUserRouteRoute,
} as any)
const LocaleHotelsSearchRoute = LocaleHotelsSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => LocaleHotelsRoute,
} as any)
const LocaleFlightsSearchRoute = LocaleFlightsSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => LocaleFlightsRoute,
} as any)
const LocaleDestinationsPromoRoute = LocaleDestinationsPromoRouteImport.update({
  id: '/destinations/promo',
  path: '/destinations/promo',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleDestinationsCountryRoute =
  LocaleDestinationsCountryRouteImport.update({
    id: '/destinations/country',
    path: '/destinations/country',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocaleAuthSignUpRoute = LocaleAuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAuthSignInRoute = LocaleAuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleInfoTrustSafetyRoute = LocaleInfoTrustSafetyRouteImport.update({
  id: '/_info/trust-safety',
  path: '/trust-safety',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleInfoTermsConditionsRoute =
  LocaleInfoTermsConditionsRouteImport.update({
    id: '/_info/terms-conditions',
    path: '/terms-conditions',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocaleInfoPrivacyPolicyRoute = LocaleInfoPrivacyPolicyRouteImport.update({
  id: '/_info/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleInfoHelpCenterRoute = LocaleInfoHelpCenterRouteImport.update({
  id: '/_info/help-center',
  path: '/help-center',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleInfoCustomerServiceRoute =
  LocaleInfoCustomerServiceRouteImport.update({
    id: '/_info/customer-service',
    path: '/customer-service',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocaleInfoContactRoute = LocaleInfoContactRouteImport.update({
  id: '/_info/contact',
  path: '/contact',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleInfoAboutRoute = LocaleInfoAboutRouteImport.update({
  id: '/_info/about',
  path: '/about',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleBookingReserveRouteRoute =
  LocaleBookingReserveRouteRouteImport.update({
    id: '/_booking/reserve',
    path: '/reserve',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocaleBookingCheckoutRouteRoute =
  LocaleBookingCheckoutRouteRouteImport.update({
    id: '/_booking/checkout',
    path: '/checkout',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocaleHotelsSearchIndexRoute = LocaleHotelsSearchIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleHotelsSearchRoute,
} as any)
const LocaleFlightsSearchIndexRoute =
  LocaleFlightsSearchIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LocaleFlightsSearchRoute,
  } as any)
const LocaleHotelsCountryIdHotelIdRoute =
  LocaleHotelsCountryIdHotelIdRouteImport.update({
    id: '/$countryId/$hotelId',
    path: '/$countryId/$hotelId',
    getParentRoute: () => LocaleHotelsRoute,
  } as any)
const LocaleBookingCheckoutFlightIdRoute =
  LocaleBookingCheckoutFlightIdRouteImport.update({
    id: '/$flightId',
    path: '/$flightId',
    getParentRoute: () => LocaleBookingCheckoutRouteRoute,
  } as any)
const LocaleBookingConfirmationWebCheckinRoute =
  LocaleBookingConfirmationWebCheckinRouteImport.update({
    id: '/_booking/_confirmation/web-checkin',
    path: '/web-checkin',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocaleBookingConfirmationOrderDetailRoute =
  LocaleBookingConfirmationOrderDetailRouteImport.update({
    id: '/_booking/_confirmation/order-detail',
    path: '/order-detail',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocaleBookingConfirmationFlightDetailsRoute =
  LocaleBookingConfirmationFlightDetailsRouteImport.update({
    id: '/_booking/_confirmation/flight-details',
    path: '/flight-details',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocaleBookingConfirmationConfirmationHotelRoute =
  LocaleBookingConfirmationConfirmationHotelRouteImport.update({
    id: '/_booking/_confirmation/confirmation-hotel',
    path: '/confirmation-hotel',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocaleBookingConfirmationConfirmationFlightRoute =
  LocaleBookingConfirmationConfirmationFlightRouteImport.update({
    id: '/_booking/_confirmation/confirmation-flight',
    path: '/confirmation-flight',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocaleBookingConfirmationConfirmationRoute =
  LocaleBookingConfirmationConfirmationRouteImport.update({
    id: '/_booking/_confirmation/confirmation',
    path: '/confirmation',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocaleBookingReservePaymentBookingIdRoute =
  LocaleBookingReservePaymentBookingIdRouteImport.update({
    id: '/payment/$bookingId',
    path: '/payment/$bookingId',
    getParentRoute: () => LocaleBookingReserveRouteRoute,
  } as any)
const LocaleBookingReserveFormBookingIdRoute =
  LocaleBookingReserveFormBookingIdRouteImport.update({
    id: '/form/$bookingId',
    path: '/form/$bookingId',
    getParentRoute: () => LocaleBookingReserveRouteRoute,
  } as any)
const LocaleBookingCheckoutTicketTypeFlightIdRoute =
  LocaleBookingCheckoutTicketTypeFlightIdRouteImport.update({
    id: '/ticket-type/$flightId',
    path: '/ticket-type/$flightId',
    getParentRoute: () => LocaleBookingCheckoutRouteRoute,
  } as any)
const LocaleBookingCheckoutSeatsFlightIdRoute =
  LocaleBookingCheckoutSeatsFlightIdRouteImport.update({
    id: '/seats/$flightId',
    path: '/seats/$flightId',
    getParentRoute: () => LocaleBookingCheckoutRouteRoute,
  } as any)
const LocaleBookingCheckoutPaymentFlightIdRoute =
  LocaleBookingCheckoutPaymentFlightIdRouteImport.update({
    id: '/payment/$flightId',
    path: '/payment/$flightId',
    getParentRoute: () => LocaleBookingCheckoutRouteRoute,
  } as any)
const LocaleBookingCheckoutPaxFlightIdRoute =
  LocaleBookingCheckoutPaxFlightIdRouteImport.update({
    id: '/pax/$flightId',
    path: '/pax/$flightId',
    getParentRoute: () => LocaleBookingCheckoutRouteRoute,
  } as any)
const LocaleBookingCheckoutExtrasFlightIdRoute =
  LocaleBookingCheckoutExtrasFlightIdRouteImport.update({
    id: '/extras/$flightId',
    path: '/extras/$flightId',
    getParentRoute: () => LocaleBookingCheckoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/user': typeof LocaleUserRouteRouteWithChildren
  '/$locale/404': typeof Locale404Route
  '/$locale/flights': typeof LocaleFlightsRouteWithChildren
  '/$locale/hotels': typeof LocaleHotelsRouteWithChildren
  '/$locale/checkout': typeof LocaleBookingCheckoutRouteRouteWithChildren
  '/$locale/reserve': typeof LocaleBookingReserveRouteRouteWithChildren
  '/$locale/about': typeof LocaleInfoAboutRoute
  '/$locale/contact': typeof LocaleInfoContactRoute
  '/$locale/customer-service': typeof LocaleInfoCustomerServiceRoute
  '/$locale/help-center': typeof LocaleInfoHelpCenterRoute
  '/$locale/privacy-policy': typeof LocaleInfoPrivacyPolicyRoute
  '/$locale/terms-conditions': typeof LocaleInfoTermsConditionsRoute
  '/$locale/trust-safety': typeof LocaleInfoTrustSafetyRoute
  '/$locale/auth/sign-in': typeof LocaleAuthSignInRoute
  '/$locale/auth/sign-up': typeof LocaleAuthSignUpRoute
  '/$locale/destinations/country': typeof LocaleDestinationsCountryRoute
  '/$locale/destinations/promo': typeof LocaleDestinationsPromoRoute
  '/$locale/flights/search': typeof LocaleFlightsSearchRouteWithChildren
  '/$locale/hotels/search': typeof LocaleHotelsSearchRouteWithChildren
  '/$locale/user/account': typeof LocaleUserAccountRoute
  '/$locale/user/review': typeof LocaleUserReviewRoute
  '/$locale/user/rewards': typeof LocaleUserRewardsRoute
  '/$locale/user/saved': typeof LocaleUserSavedRoute
  '/$locale/user/settings': typeof LocaleUserSettingsRoute
  '/$locale/user/trips': typeof LocaleUserTripsRoute
  '/$locale/flights/': typeof LocaleFlightsIndexRoute
  '/$locale/hotels/': typeof LocaleHotelsIndexRoute
  '/$locale/user/': typeof LocaleUserIndexRoute
  '/$locale/confirmation': typeof LocaleBookingConfirmationConfirmationRoute
  '/$locale/confirmation-flight': typeof LocaleBookingConfirmationConfirmationFlightRoute
  '/$locale/confirmation-hotel': typeof LocaleBookingConfirmationConfirmationHotelRoute
  '/$locale/flight-details': typeof LocaleBookingConfirmationFlightDetailsRoute
  '/$locale/order-detail': typeof LocaleBookingConfirmationOrderDetailRoute
  '/$locale/web-checkin': typeof LocaleBookingConfirmationWebCheckinRoute
  '/$locale/checkout/$flightId': typeof LocaleBookingCheckoutFlightIdRoute
  '/$locale/hotels/$countryId/$hotelId': typeof LocaleHotelsCountryIdHotelIdRoute
  '/$locale/flights/search/': typeof LocaleFlightsSearchIndexRoute
  '/$locale/hotels/search/': typeof LocaleHotelsSearchIndexRoute
  '/$locale/checkout/extras/$flightId': typeof LocaleBookingCheckoutExtrasFlightIdRoute
  '/$locale/checkout/pax/$flightId': typeof LocaleBookingCheckoutPaxFlightIdRoute
  '/$locale/checkout/payment/$flightId': typeof LocaleBookingCheckoutPaymentFlightIdRoute
  '/$locale/checkout/seats/$flightId': typeof LocaleBookingCheckoutSeatsFlightIdRoute
  '/$locale/checkout/ticket-type/$flightId': typeof LocaleBookingCheckoutTicketTypeFlightIdRoute
  '/$locale/reserve/form/$bookingId': typeof LocaleBookingReserveFormBookingIdRoute
  '/$locale/reserve/payment/$bookingId': typeof LocaleBookingReservePaymentBookingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/404': typeof Locale404Route
  '/$locale/checkout': typeof LocaleBookingCheckoutRouteRouteWithChildren
  '/$locale/reserve': typeof LocaleBookingReserveRouteRouteWithChildren
  '/$locale/about': typeof LocaleInfoAboutRoute
  '/$locale/contact': typeof LocaleInfoContactRoute
  '/$locale/customer-service': typeof LocaleInfoCustomerServiceRoute
  '/$locale/help-center': typeof LocaleInfoHelpCenterRoute
  '/$locale/privacy-policy': typeof LocaleInfoPrivacyPolicyRoute
  '/$locale/terms-conditions': typeof LocaleInfoTermsConditionsRoute
  '/$locale/trust-safety': typeof LocaleInfoTrustSafetyRoute
  '/$locale/auth/sign-in': typeof LocaleAuthSignInRoute
  '/$locale/auth/sign-up': typeof LocaleAuthSignUpRoute
  '/$locale/destinations/country': typeof LocaleDestinationsCountryRoute
  '/$locale/destinations/promo': typeof LocaleDestinationsPromoRoute
  '/$locale/user/account': typeof LocaleUserAccountRoute
  '/$locale/user/review': typeof LocaleUserReviewRoute
  '/$locale/user/rewards': typeof LocaleUserRewardsRoute
  '/$locale/user/saved': typeof LocaleUserSavedRoute
  '/$locale/user/settings': typeof LocaleUserSettingsRoute
  '/$locale/user/trips': typeof LocaleUserTripsRoute
  '/$locale/flights': typeof LocaleFlightsIndexRoute
  '/$locale/hotels': typeof LocaleHotelsIndexRoute
  '/$locale/user': typeof LocaleUserIndexRoute
  '/$locale/confirmation': typeof LocaleBookingConfirmationConfirmationRoute
  '/$locale/confirmation-flight': typeof LocaleBookingConfirmationConfirmationFlightRoute
  '/$locale/confirmation-hotel': typeof LocaleBookingConfirmationConfirmationHotelRoute
  '/$locale/flight-details': typeof LocaleBookingConfirmationFlightDetailsRoute
  '/$locale/order-detail': typeof LocaleBookingConfirmationOrderDetailRoute
  '/$locale/web-checkin': typeof LocaleBookingConfirmationWebCheckinRoute
  '/$locale/checkout/$flightId': typeof LocaleBookingCheckoutFlightIdRoute
  '/$locale/hotels/$countryId/$hotelId': typeof LocaleHotelsCountryIdHotelIdRoute
  '/$locale/flights/search': typeof LocaleFlightsSearchIndexRoute
  '/$locale/hotels/search': typeof LocaleHotelsSearchIndexRoute
  '/$locale/checkout/extras/$flightId': typeof LocaleBookingCheckoutExtrasFlightIdRoute
  '/$locale/checkout/pax/$flightId': typeof LocaleBookingCheckoutPaxFlightIdRoute
  '/$locale/checkout/payment/$flightId': typeof LocaleBookingCheckoutPaymentFlightIdRoute
  '/$locale/checkout/seats/$flightId': typeof LocaleBookingCheckoutSeatsFlightIdRoute
  '/$locale/checkout/ticket-type/$flightId': typeof LocaleBookingCheckoutTicketTypeFlightIdRoute
  '/$locale/reserve/form/$bookingId': typeof LocaleBookingReserveFormBookingIdRoute
  '/$locale/reserve/payment/$bookingId': typeof LocaleBookingReservePaymentBookingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/user': typeof LocaleUserRouteRouteWithChildren
  '/$locale/404': typeof Locale404Route
  '/$locale/flights': typeof LocaleFlightsRouteWithChildren
  '/$locale/hotels': typeof LocaleHotelsRouteWithChildren
  '/$locale/_booking/checkout': typeof LocaleBookingCheckoutRouteRouteWithChildren
  '/$locale/_booking/reserve': typeof LocaleBookingReserveRouteRouteWithChildren
  '/$locale/_info/about': typeof LocaleInfoAboutRoute
  '/$locale/_info/contact': typeof LocaleInfoContactRoute
  '/$locale/_info/customer-service': typeof LocaleInfoCustomerServiceRoute
  '/$locale/_info/help-center': typeof LocaleInfoHelpCenterRoute
  '/$locale/_info/privacy-policy': typeof LocaleInfoPrivacyPolicyRoute
  '/$locale/_info/terms-conditions': typeof LocaleInfoTermsConditionsRoute
  '/$locale/_info/trust-safety': typeof LocaleInfoTrustSafetyRoute
  '/$locale/auth/sign-in': typeof LocaleAuthSignInRoute
  '/$locale/auth/sign-up': typeof LocaleAuthSignUpRoute
  '/$locale/destinations/country': typeof LocaleDestinationsCountryRoute
  '/$locale/destinations/promo': typeof LocaleDestinationsPromoRoute
  '/$locale/flights/search': typeof LocaleFlightsSearchRouteWithChildren
  '/$locale/hotels/search': typeof LocaleHotelsSearchRouteWithChildren
  '/$locale/user/account': typeof LocaleUserAccountRoute
  '/$locale/user/review': typeof LocaleUserReviewRoute
  '/$locale/user/rewards': typeof LocaleUserRewardsRoute
  '/$locale/user/saved': typeof LocaleUserSavedRoute
  '/$locale/user/settings': typeof LocaleUserSettingsRoute
  '/$locale/user/trips': typeof LocaleUserTripsRoute
  '/$locale/flights/': typeof LocaleFlightsIndexRoute
  '/$locale/hotels/': typeof LocaleHotelsIndexRoute
  '/$locale/user/': typeof LocaleUserIndexRoute
  '/$locale/_booking/_confirmation/confirmation': typeof LocaleBookingConfirmationConfirmationRoute
  '/$locale/_booking/_confirmation/confirmation-flight': typeof LocaleBookingConfirmationConfirmationFlightRoute
  '/$locale/_booking/_confirmation/confirmation-hotel': typeof LocaleBookingConfirmationConfirmationHotelRoute
  '/$locale/_booking/_confirmation/flight-details': typeof LocaleBookingConfirmationFlightDetailsRoute
  '/$locale/_booking/_confirmation/order-detail': typeof LocaleBookingConfirmationOrderDetailRoute
  '/$locale/_booking/_confirmation/web-checkin': typeof LocaleBookingConfirmationWebCheckinRoute
  '/$locale/_booking/checkout/$flightId': typeof LocaleBookingCheckoutFlightIdRoute
  '/$locale/hotels/$countryId/$hotelId': typeof LocaleHotelsCountryIdHotelIdRoute
  '/$locale/flights/search/': typeof LocaleFlightsSearchIndexRoute
  '/$locale/hotels/search/': typeof LocaleHotelsSearchIndexRoute
  '/$locale/_booking/checkout/extras/$flightId': typeof LocaleBookingCheckoutExtrasFlightIdRoute
  '/$locale/_booking/checkout/pax/$flightId': typeof LocaleBookingCheckoutPaxFlightIdRoute
  '/$locale/_booking/checkout/payment/$flightId': typeof LocaleBookingCheckoutPaymentFlightIdRoute
  '/$locale/_booking/checkout/seats/$flightId': typeof LocaleBookingCheckoutSeatsFlightIdRoute
  '/$locale/_booking/checkout/ticket-type/$flightId': typeof LocaleBookingCheckoutTicketTypeFlightIdRoute
  '/$locale/_booking/reserve/form/$bookingId': typeof LocaleBookingReserveFormBookingIdRoute
  '/$locale/_booking/reserve/payment/$bookingId': typeof LocaleBookingReservePaymentBookingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$locale/user'
    | '/$locale/404'
    | '/$locale/flights'
    | '/$locale/hotels'
    | '/$locale/checkout'
    | '/$locale/reserve'
    | '/$locale/about'
    | '/$locale/contact'
    | '/$locale/customer-service'
    | '/$locale/help-center'
    | '/$locale/privacy-policy'
    | '/$locale/terms-conditions'
    | '/$locale/trust-safety'
    | '/$locale/auth/sign-in'
    | '/$locale/auth/sign-up'
    | '/$locale/destinations/country'
    | '/$locale/destinations/promo'
    | '/$locale/flights/search'
    | '/$locale/hotels/search'
    | '/$locale/user/account'
    | '/$locale/user/review'
    | '/$locale/user/rewards'
    | '/$locale/user/saved'
    | '/$locale/user/settings'
    | '/$locale/user/trips'
    | '/$locale/flights/'
    | '/$locale/hotels/'
    | '/$locale/user/'
    | '/$locale/confirmation'
    | '/$locale/confirmation-flight'
    | '/$locale/confirmation-hotel'
    | '/$locale/flight-details'
    | '/$locale/order-detail'
    | '/$locale/web-checkin'
    | '/$locale/checkout/$flightId'
    | '/$locale/hotels/$countryId/$hotelId'
    | '/$locale/flights/search/'
    | '/$locale/hotels/search/'
    | '/$locale/checkout/extras/$flightId'
    | '/$locale/checkout/pax/$flightId'
    | '/$locale/checkout/payment/$flightId'
    | '/$locale/checkout/seats/$flightId'
    | '/$locale/checkout/ticket-type/$flightId'
    | '/$locale/reserve/form/$bookingId'
    | '/$locale/reserve/payment/$bookingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale'
    | '/$locale/404'
    | '/$locale/checkout'
    | '/$locale/reserve'
    | '/$locale/about'
    | '/$locale/contact'
    | '/$locale/customer-service'
    | '/$locale/help-center'
    | '/$locale/privacy-policy'
    | '/$locale/terms-conditions'
    | '/$locale/trust-safety'
    | '/$locale/auth/sign-in'
    | '/$locale/auth/sign-up'
    | '/$locale/destinations/country'
    | '/$locale/destinations/promo'
    | '/$locale/user/account'
    | '/$locale/user/review'
    | '/$locale/user/rewards'
    | '/$locale/user/saved'
    | '/$locale/user/settings'
    | '/$locale/user/trips'
    | '/$locale/flights'
    | '/$locale/hotels'
    | '/$locale/user'
    | '/$locale/confirmation'
    | '/$locale/confirmation-flight'
    | '/$locale/confirmation-hotel'
    | '/$locale/flight-details'
    | '/$locale/order-detail'
    | '/$locale/web-checkin'
    | '/$locale/checkout/$flightId'
    | '/$locale/hotels/$countryId/$hotelId'
    | '/$locale/flights/search'
    | '/$locale/hotels/search'
    | '/$locale/checkout/extras/$flightId'
    | '/$locale/checkout/pax/$flightId'
    | '/$locale/checkout/payment/$flightId'
    | '/$locale/checkout/seats/$flightId'
    | '/$locale/checkout/ticket-type/$flightId'
    | '/$locale/reserve/form/$bookingId'
    | '/$locale/reserve/payment/$bookingId'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/$locale/user'
    | '/$locale/404'
    | '/$locale/flights'
    | '/$locale/hotels'
    | '/$locale/_booking/checkout'
    | '/$locale/_booking/reserve'
    | '/$locale/_info/about'
    | '/$locale/_info/contact'
    | '/$locale/_info/customer-service'
    | '/$locale/_info/help-center'
    | '/$locale/_info/privacy-policy'
    | '/$locale/_info/terms-conditions'
    | '/$locale/_info/trust-safety'
    | '/$locale/auth/sign-in'
    | '/$locale/auth/sign-up'
    | '/$locale/destinations/country'
    | '/$locale/destinations/promo'
    | '/$locale/flights/search'
    | '/$locale/hotels/search'
    | '/$locale/user/account'
    | '/$locale/user/review'
    | '/$locale/user/rewards'
    | '/$locale/user/saved'
    | '/$locale/user/settings'
    | '/$locale/user/trips'
    | '/$locale/flights/'
    | '/$locale/hotels/'
    | '/$locale/user/'
    | '/$locale/_booking/_confirmation/confirmation'
    | '/$locale/_booking/_confirmation/confirmation-flight'
    | '/$locale/_booking/_confirmation/confirmation-hotel'
    | '/$locale/_booking/_confirmation/flight-details'
    | '/$locale/_booking/_confirmation/order-detail'
    | '/$locale/_booking/_confirmation/web-checkin'
    | '/$locale/_booking/checkout/$flightId'
    | '/$locale/hotels/$countryId/$hotelId'
    | '/$locale/flights/search/'
    | '/$locale/hotels/search/'
    | '/$locale/_booking/checkout/extras/$flightId'
    | '/$locale/_booking/checkout/pax/$flightId'
    | '/$locale/_booking/checkout/payment/$flightId'
    | '/$locale/_booking/checkout/seats/$flightId'
    | '/$locale/_booking/checkout/ticket-type/$flightId'
    | '/$locale/_booking/reserve/form/$bookingId'
    | '/$locale/_booking/reserve/payment/$bookingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/hotels': {
      id: '/$locale/hotels'
      path: '/hotels'
      fullPath: '/$locale/hotels'
      preLoaderRoute: typeof LocaleHotelsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/flights': {
      id: '/$locale/flights'
      path: '/flights'
      fullPath: '/$locale/flights'
      preLoaderRoute: typeof LocaleFlightsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/404': {
      id: '/$locale/404'
      path: '/404'
      fullPath: '/$locale/404'
      preLoaderRoute: typeof Locale404RouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/user': {
      id: '/$locale/user'
      path: '/user'
      fullPath: '/$locale/user'
      preLoaderRoute: typeof LocaleUserRouteRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/user/': {
      id: '/$locale/user/'
      path: '/'
      fullPath: '/$locale/user/'
      preLoaderRoute: typeof LocaleUserIndexRouteImport
      parentRoute: typeof LocaleUserRouteRoute
    }
    '/$locale/hotels/': {
      id: '/$locale/hotels/'
      path: '/'
      fullPath: '/$locale/hotels/'
      preLoaderRoute: typeof LocaleHotelsIndexRouteImport
      parentRoute: typeof LocaleHotelsRoute
    }
    '/$locale/flights/': {
      id: '/$locale/flights/'
      path: '/'
      fullPath: '/$locale/flights/'
      preLoaderRoute: typeof LocaleFlightsIndexRouteImport
      parentRoute: typeof LocaleFlightsRoute
    }
    '/$locale/user/trips': {
      id: '/$locale/user/trips'
      path: '/trips'
      fullPath: '/$locale/user/trips'
      preLoaderRoute: typeof LocaleUserTripsRouteImport
      parentRoute: typeof LocaleUserRouteRoute
    }
    '/$locale/user/settings': {
      id: '/$locale/user/settings'
      path: '/settings'
      fullPath: '/$locale/user/settings'
      preLoaderRoute: typeof LocaleUserSettingsRouteImport
      parentRoute: typeof LocaleUserRouteRoute
    }
    '/$locale/user/saved': {
      id: '/$locale/user/saved'
      path: '/saved'
      fullPath: '/$locale/user/saved'
      preLoaderRoute: typeof LocaleUserSavedRouteImport
      parentRoute: typeof LocaleUserRouteRoute
    }
    '/$locale/user/rewards': {
      id: '/$locale/user/rewards'
      path: '/rewards'
      fullPath: '/$locale/user/rewards'
      preLoaderRoute: typeof LocaleUserRewardsRouteImport
      parentRoute: typeof LocaleUserRouteRoute
    }
    '/$locale/user/review': {
      id: '/$locale/user/review'
      path: '/review'
      fullPath: '/$locale/user/review'
      preLoaderRoute: typeof LocaleUserReviewRouteImport
      parentRoute: typeof LocaleUserRouteRoute
    }
    '/$locale/user/account': {
      id: '/$locale/user/account'
      path: '/account'
      fullPath: '/$locale/user/account'
      preLoaderRoute: typeof LocaleUserAccountRouteImport
      parentRoute: typeof LocaleUserRouteRoute
    }
    '/$locale/hotels/search': {
      id: '/$locale/hotels/search'
      path: '/search'
      fullPath: '/$locale/hotels/search'
      preLoaderRoute: typeof LocaleHotelsSearchRouteImport
      parentRoute: typeof LocaleHotelsRoute
    }
    '/$locale/flights/search': {
      id: '/$locale/flights/search'
      path: '/search'
      fullPath: '/$locale/flights/search'
      preLoaderRoute: typeof LocaleFlightsSearchRouteImport
      parentRoute: typeof LocaleFlightsRoute
    }
    '/$locale/destinations/promo': {
      id: '/$locale/destinations/promo'
      path: '/destinations/promo'
      fullPath: '/$locale/destinations/promo'
      preLoaderRoute: typeof LocaleDestinationsPromoRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/destinations/country': {
      id: '/$locale/destinations/country'
      path: '/destinations/country'
      fullPath: '/$locale/destinations/country'
      preLoaderRoute: typeof LocaleDestinationsCountryRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/auth/sign-up': {
      id: '/$locale/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/$locale/auth/sign-up'
      preLoaderRoute: typeof LocaleAuthSignUpRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/auth/sign-in': {
      id: '/$locale/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/$locale/auth/sign-in'
      preLoaderRoute: typeof LocaleAuthSignInRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/_info/trust-safety': {
      id: '/$locale/_info/trust-safety'
      path: '/trust-safety'
      fullPath: '/$locale/trust-safety'
      preLoaderRoute: typeof LocaleInfoTrustSafetyRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/_info/terms-conditions': {
      id: '/$locale/_info/terms-conditions'
      path: '/terms-conditions'
      fullPath: '/$locale/terms-conditions'
      preLoaderRoute: typeof LocaleInfoTermsConditionsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/_info/privacy-policy': {
      id: '/$locale/_info/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/$locale/privacy-policy'
      preLoaderRoute: typeof LocaleInfoPrivacyPolicyRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/_info/help-center': {
      id: '/$locale/_info/help-center'
      path: '/help-center'
      fullPath: '/$locale/help-center'
      preLoaderRoute: typeof LocaleInfoHelpCenterRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/_info/customer-service': {
      id: '/$locale/_info/customer-service'
      path: '/customer-service'
      fullPath: '/$locale/customer-service'
      preLoaderRoute: typeof LocaleInfoCustomerServiceRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/_info/contact': {
      id: '/$locale/_info/contact'
      path: '/contact'
      fullPath: '/$locale/contact'
      preLoaderRoute: typeof LocaleInfoContactRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/_info/about': {
      id: '/$locale/_info/about'
      path: '/about'
      fullPath: '/$locale/about'
      preLoaderRoute: typeof LocaleInfoAboutRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/_booking/reserve': {
      id: '/$locale/_booking/reserve'
      path: '/reserve'
      fullPath: '/$locale/reserve'
      preLoaderRoute: typeof LocaleBookingReserveRouteRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/_booking/checkout': {
      id: '/$locale/_booking/checkout'
      path: '/checkout'
      fullPath: '/$locale/checkout'
      preLoaderRoute: typeof LocaleBookingCheckoutRouteRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/hotels/search/': {
      id: '/$locale/hotels/search/'
      path: '/'
      fullPath: '/$locale/hotels/search/'
      preLoaderRoute: typeof LocaleHotelsSearchIndexRouteImport
      parentRoute: typeof LocaleHotelsSearchRoute
    }
    '/$locale/flights/search/': {
      id: '/$locale/flights/search/'
      path: '/'
      fullPath: '/$locale/flights/search/'
      preLoaderRoute: typeof LocaleFlightsSearchIndexRouteImport
      parentRoute: typeof LocaleFlightsSearchRoute
    }
    '/$locale/hotels/$countryId/$hotelId': {
      id: '/$locale/hotels/$countryId/$hotelId'
      path: '/$countryId/$hotelId'
      fullPath: '/$locale/hotels/$countryId/$hotelId'
      preLoaderRoute: typeof LocaleHotelsCountryIdHotelIdRouteImport
      parentRoute: typeof LocaleHotelsRoute
    }
    '/$locale/_booking/checkout/$flightId': {
      id: '/$locale/_booking/checkout/$flightId'
      path: '/$flightId'
      fullPath: '/$locale/checkout/$flightId'
      preLoaderRoute: typeof LocaleBookingCheckoutFlightIdRouteImport
      parentRoute: typeof LocaleBookingCheckoutRouteRoute
    }
    '/$locale/_booking/_confirmation/web-checkin': {
      id: '/$locale/_booking/_confirmation/web-checkin'
      path: '/web-checkin'
      fullPath: '/$locale/web-checkin'
      preLoaderRoute: typeof LocaleBookingConfirmationWebCheckinRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/_booking/_confirmation/order-detail': {
      id: '/$locale/_booking/_confirmation/order-detail'
      path: '/order-detail'
      fullPath: '/$locale/order-detail'
      preLoaderRoute: typeof LocaleBookingConfirmationOrderDetailRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/_booking/_confirmation/flight-details': {
      id: '/$locale/_booking/_confirmation/flight-details'
      path: '/flight-details'
      fullPath: '/$locale/flight-details'
      preLoaderRoute: typeof LocaleBookingConfirmationFlightDetailsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/_booking/_confirmation/confirmation-hotel': {
      id: '/$locale/_booking/_confirmation/confirmation-hotel'
      path: '/confirmation-hotel'
      fullPath: '/$locale/confirmation-hotel'
      preLoaderRoute: typeof LocaleBookingConfirmationConfirmationHotelRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/_booking/_confirmation/confirmation-flight': {
      id: '/$locale/_booking/_confirmation/confirmation-flight'
      path: '/confirmation-flight'
      fullPath: '/$locale/confirmation-flight'
      preLoaderRoute: typeof LocaleBookingConfirmationConfirmationFlightRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/_booking/_confirmation/confirmation': {
      id: '/$locale/_booking/_confirmation/confirmation'
      path: '/confirmation'
      fullPath: '/$locale/confirmation'
      preLoaderRoute: typeof LocaleBookingConfirmationConfirmationRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/_booking/reserve/payment/$bookingId': {
      id: '/$locale/_booking/reserve/payment/$bookingId'
      path: '/payment/$bookingId'
      fullPath: '/$locale/reserve/payment/$bookingId'
      preLoaderRoute: typeof LocaleBookingReservePaymentBookingIdRouteImport
      parentRoute: typeof LocaleBookingReserveRouteRoute
    }
    '/$locale/_booking/reserve/form/$bookingId': {
      id: '/$locale/_booking/reserve/form/$bookingId'
      path: '/form/$bookingId'
      fullPath: '/$locale/reserve/form/$bookingId'
      preLoaderRoute: typeof LocaleBookingReserveFormBookingIdRouteImport
      parentRoute: typeof LocaleBookingReserveRouteRoute
    }
    '/$locale/_booking/checkout/ticket-type/$flightId': {
      id: '/$locale/_booking/checkout/ticket-type/$flightId'
      path: '/ticket-type/$flightId'
      fullPath: '/$locale/checkout/ticket-type/$flightId'
      preLoaderRoute: typeof LocaleBookingCheckoutTicketTypeFlightIdRouteImport
      parentRoute: typeof LocaleBookingCheckoutRouteRoute
    }
    '/$locale/_booking/checkout/seats/$flightId': {
      id: '/$locale/_booking/checkout/seats/$flightId'
      path: '/seats/$flightId'
      fullPath: '/$locale/checkout/seats/$flightId'
      preLoaderRoute: typeof LocaleBookingCheckoutSeatsFlightIdRouteImport
      parentRoute: typeof LocaleBookingCheckoutRouteRoute
    }
    '/$locale/_booking/checkout/payment/$flightId': {
      id: '/$locale/_booking/checkout/payment/$flightId'
      path: '/payment/$flightId'
      fullPath: '/$locale/checkout/payment/$flightId'
      preLoaderRoute: typeof LocaleBookingCheckoutPaymentFlightIdRouteImport
      parentRoute: typeof LocaleBookingCheckoutRouteRoute
    }
    '/$locale/_booking/checkout/pax/$flightId': {
      id: '/$locale/_booking/checkout/pax/$flightId'
      path: '/pax/$flightId'
      fullPath: '/$locale/checkout/pax/$flightId'
      preLoaderRoute: typeof LocaleBookingCheckoutPaxFlightIdRouteImport
      parentRoute: typeof LocaleBookingCheckoutRouteRoute
    }
    '/$locale/_booking/checkout/extras/$flightId': {
      id: '/$locale/_booking/checkout/extras/$flightId'
      path: '/extras/$flightId'
      fullPath: '/$locale/checkout/extras/$flightId'
      preLoaderRoute: typeof LocaleBookingCheckoutExtrasFlightIdRouteImport
      parentRoute: typeof LocaleBookingCheckoutRouteRoute
    }
  }
}

interface LocaleUserRouteRouteChildren {
  LocaleUserAccountRoute: typeof LocaleUserAccountRoute
  LocaleUserReviewRoute: typeof LocaleUserReviewRoute
  LocaleUserRewardsRoute: typeof LocaleUserRewardsRoute
  LocaleUserSavedRoute: typeof LocaleUserSavedRoute
  LocaleUserSettingsRoute: typeof LocaleUserSettingsRoute
  LocaleUserTripsRoute: typeof LocaleUserTripsRoute
  LocaleUserIndexRoute: typeof LocaleUserIndexRoute
}

const LocaleUserRouteRouteChildren: LocaleUserRouteRouteChildren = {
  LocaleUserAccountRoute: LocaleUserAccountRoute,
  LocaleUserReviewRoute: LocaleUserReviewRoute,
  LocaleUserRewardsRoute: LocaleUserRewardsRoute,
  LocaleUserSavedRoute: LocaleUserSavedRoute,
  LocaleUserSettingsRoute: LocaleUserSettingsRoute,
  LocaleUserTripsRoute: LocaleUserTripsRoute,
  LocaleUserIndexRoute: LocaleUserIndexRoute,
}

const LocaleUserRouteRouteWithChildren = LocaleUserRouteRoute._addFileChildren(
  LocaleUserRouteRouteChildren,
)

interface LocaleFlightsSearchRouteChildren {
  LocaleFlightsSearchIndexRoute: typeof LocaleFlightsSearchIndexRoute
}

const LocaleFlightsSearchRouteChildren: LocaleFlightsSearchRouteChildren = {
  LocaleFlightsSearchIndexRoute: LocaleFlightsSearchIndexRoute,
}

const LocaleFlightsSearchRouteWithChildren =
  LocaleFlightsSearchRoute._addFileChildren(LocaleFlightsSearchRouteChildren)

interface LocaleFlightsRouteChildren {
  LocaleFlightsSearchRoute: typeof LocaleFlightsSearchRouteWithChildren
  LocaleFlightsIndexRoute: typeof LocaleFlightsIndexRoute
}

const LocaleFlightsRouteChildren: LocaleFlightsRouteChildren = {
  LocaleFlightsSearchRoute: LocaleFlightsSearchRouteWithChildren,
  LocaleFlightsIndexRoute: LocaleFlightsIndexRoute,
}

const LocaleFlightsRouteWithChildren = LocaleFlightsRoute._addFileChildren(
  LocaleFlightsRouteChildren,
)

interface LocaleHotelsSearchRouteChildren {
  LocaleHotelsSearchIndexRoute: typeof LocaleHotelsSearchIndexRoute
}

const LocaleHotelsSearchRouteChildren: LocaleHotelsSearchRouteChildren = {
  LocaleHotelsSearchIndexRoute: LocaleHotelsSearchIndexRoute,
}

const LocaleHotelsSearchRouteWithChildren =
  LocaleHotelsSearchRoute._addFileChildren(LocaleHotelsSearchRouteChildren)

interface LocaleHotelsRouteChildren {
  LocaleHotelsSearchRoute: typeof LocaleHotelsSearchRouteWithChildren
  LocaleHotelsIndexRoute: typeof LocaleHotelsIndexRoute
  LocaleHotelsCountryIdHotelIdRoute: typeof LocaleHotelsCountryIdHotelIdRoute
}

const LocaleHotelsRouteChildren: LocaleHotelsRouteChildren = {
  LocaleHotelsSearchRoute: LocaleHotelsSearchRouteWithChildren,
  LocaleHotelsIndexRoute: LocaleHotelsIndexRoute,
  LocaleHotelsCountryIdHotelIdRoute: LocaleHotelsCountryIdHotelIdRoute,
}

const LocaleHotelsRouteWithChildren = LocaleHotelsRoute._addFileChildren(
  LocaleHotelsRouteChildren,
)

interface LocaleBookingCheckoutRouteRouteChildren {
  LocaleBookingCheckoutFlightIdRoute: typeof LocaleBookingCheckoutFlightIdRoute
  LocaleBookingCheckoutExtrasFlightIdRoute: typeof LocaleBookingCheckoutExtrasFlightIdRoute
  LocaleBookingCheckoutPaxFlightIdRoute: typeof LocaleBookingCheckoutPaxFlightIdRoute
  LocaleBookingCheckoutPaymentFlightIdRoute: typeof LocaleBookingCheckoutPaymentFlightIdRoute
  LocaleBookingCheckoutSeatsFlightIdRoute: typeof LocaleBookingCheckoutSeatsFlightIdRoute
  LocaleBookingCheckoutTicketTypeFlightIdRoute: typeof LocaleBookingCheckoutTicketTypeFlightIdRoute
}

const LocaleBookingCheckoutRouteRouteChildren: LocaleBookingCheckoutRouteRouteChildren =
  {
    LocaleBookingCheckoutFlightIdRoute: LocaleBookingCheckoutFlightIdRoute,
    LocaleBookingCheckoutExtrasFlightIdRoute:
      LocaleBookingCheckoutExtrasFlightIdRoute,
    LocaleBookingCheckoutPaxFlightIdRoute:
      LocaleBookingCheckoutPaxFlightIdRoute,
    LocaleBookingCheckoutPaymentFlightIdRoute:
      LocaleBookingCheckoutPaymentFlightIdRoute,
    LocaleBookingCheckoutSeatsFlightIdRoute:
      LocaleBookingCheckoutSeatsFlightIdRoute,
    LocaleBookingCheckoutTicketTypeFlightIdRoute:
      LocaleBookingCheckoutTicketTypeFlightIdRoute,
  }

const LocaleBookingCheckoutRouteRouteWithChildren =
  LocaleBookingCheckoutRouteRoute._addFileChildren(
    LocaleBookingCheckoutRouteRouteChildren,
  )

interface LocaleBookingReserveRouteRouteChildren {
  LocaleBookingReserveFormBookingIdRoute: typeof LocaleBookingReserveFormBookingIdRoute
  LocaleBookingReservePaymentBookingIdRoute: typeof LocaleBookingReservePaymentBookingIdRoute
}

const LocaleBookingReserveRouteRouteChildren: LocaleBookingReserveRouteRouteChildren =
  {
    LocaleBookingReserveFormBookingIdRoute:
      LocaleBookingReserveFormBookingIdRoute,
    LocaleBookingReservePaymentBookingIdRoute:
      LocaleBookingReservePaymentBookingIdRoute,
  }

const LocaleBookingReserveRouteRouteWithChildren =
  LocaleBookingReserveRouteRoute._addFileChildren(
    LocaleBookingReserveRouteRouteChildren,
  )

interface LocaleRouteChildren {
  LocaleUserRouteRoute: typeof LocaleUserRouteRouteWithChildren
  Locale404Route: typeof Locale404Route
  LocaleFlightsRoute: typeof LocaleFlightsRouteWithChildren
  LocaleHotelsRoute: typeof LocaleHotelsRouteWithChildren
  LocaleBookingCheckoutRouteRoute: typeof LocaleBookingCheckoutRouteRouteWithChildren
  LocaleBookingReserveRouteRoute: typeof LocaleBookingReserveRouteRouteWithChildren
  LocaleInfoAboutRoute: typeof LocaleInfoAboutRoute
  LocaleInfoContactRoute: typeof LocaleInfoContactRoute
  LocaleInfoCustomerServiceRoute: typeof LocaleInfoCustomerServiceRoute
  LocaleInfoHelpCenterRoute: typeof LocaleInfoHelpCenterRoute
  LocaleInfoPrivacyPolicyRoute: typeof LocaleInfoPrivacyPolicyRoute
  LocaleInfoTermsConditionsRoute: typeof LocaleInfoTermsConditionsRoute
  LocaleInfoTrustSafetyRoute: typeof LocaleInfoTrustSafetyRoute
  LocaleAuthSignInRoute: typeof LocaleAuthSignInRoute
  LocaleAuthSignUpRoute: typeof LocaleAuthSignUpRoute
  LocaleDestinationsCountryRoute: typeof LocaleDestinationsCountryRoute
  LocaleDestinationsPromoRoute: typeof LocaleDestinationsPromoRoute
  LocaleBookingConfirmationConfirmationRoute: typeof LocaleBookingConfirmationConfirmationRoute
  LocaleBookingConfirmationConfirmationFlightRoute: typeof LocaleBookingConfirmationConfirmationFlightRoute
  LocaleBookingConfirmationConfirmationHotelRoute: typeof LocaleBookingConfirmationConfirmationHotelRoute
  LocaleBookingConfirmationFlightDetailsRoute: typeof LocaleBookingConfirmationFlightDetailsRoute
  LocaleBookingConfirmationOrderDetailRoute: typeof LocaleBookingConfirmationOrderDetailRoute
  LocaleBookingConfirmationWebCheckinRoute: typeof LocaleBookingConfirmationWebCheckinRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleUserRouteRoute: LocaleUserRouteRouteWithChildren,
  Locale404Route: Locale404Route,
  LocaleFlightsRoute: LocaleFlightsRouteWithChildren,
  LocaleHotelsRoute: LocaleHotelsRouteWithChildren,
  LocaleBookingCheckoutRouteRoute: LocaleBookingCheckoutRouteRouteWithChildren,
  LocaleBookingReserveRouteRoute: LocaleBookingReserveRouteRouteWithChildren,
  LocaleInfoAboutRoute: LocaleInfoAboutRoute,
  LocaleInfoContactRoute: LocaleInfoContactRoute,
  LocaleInfoCustomerServiceRoute: LocaleInfoCustomerServiceRoute,
  LocaleInfoHelpCenterRoute: LocaleInfoHelpCenterRoute,
  LocaleInfoPrivacyPolicyRoute: LocaleInfoPrivacyPolicyRoute,
  LocaleInfoTermsConditionsRoute: LocaleInfoTermsConditionsRoute,
  LocaleInfoTrustSafetyRoute: LocaleInfoTrustSafetyRoute,
  LocaleAuthSignInRoute: LocaleAuthSignInRoute,
  LocaleAuthSignUpRoute: LocaleAuthSignUpRoute,
  LocaleDestinationsCountryRoute: LocaleDestinationsCountryRoute,
  LocaleDestinationsPromoRoute: LocaleDestinationsPromoRoute,
  LocaleBookingConfirmationConfirmationRoute:
    LocaleBookingConfirmationConfirmationRoute,
  LocaleBookingConfirmationConfirmationFlightRoute:
    LocaleBookingConfirmationConfirmationFlightRoute,
  LocaleBookingConfirmationConfirmationHotelRoute:
    LocaleBookingConfirmationConfirmationHotelRoute,
  LocaleBookingConfirmationFlightDetailsRoute:
    LocaleBookingConfirmationFlightDetailsRoute,
  LocaleBookingConfirmationOrderDetailRoute:
    LocaleBookingConfirmationOrderDetailRoute,
  LocaleBookingConfirmationWebCheckinRoute:
    LocaleBookingConfirmationWebCheckinRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
